# generic font configuration library - runtime
package: libfontconfig1

essential:
  - libfontconfig1_copyright

slices:
  libs:
    essential:
      - libc6_libs
      - libexpat1_libs
      - libfreetype6_libs
      - fontconfig-config_config
    contents:
      /usr/lib/*-linux-*/libfontconfig.so.1*:

  copyright:
    contents:
      /usr/share/doc/libfontconfig1/copyright:
